### ISSUE TITLE
Dead Screen

### ISSUE THREAD

**Issue by DerHobbs** [goncalobsccosta/vorp-core-lua#2]
Sometimes when you're dead you don't get anything displayed (it doesn't show you're dead, and it doesn't show the time until you respawn), you lie there with a gray screen, but there's nothing there flip it off and not always, unfortunately, there is no error message.

**Comment by goncalobsccosta** [comment]
hey, do you have any errors displayed in client console?

**Comment by DerHobbs** [comment]
Unfortunately no, there are absolutely no errors, everything works perfectly 20 times and then at some point there is simply no more text when you are dead

**Comment by DerHobbs** [comment]
A player sends me this, not sure if it's related

https://cdn.discordapp.com/attachments/935989307683004426/950457846082981938/unknown.png
